// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nS579jUK46wfNtUsYq4qFui8bBiRsws',
    appId: '1:255395342604:web:225f0e20966a0c39f10129',
    messagingSenderId: '255395342604',
    projectId: 'datedawn',
    authDomain: 'datedawn.firebaseapp.com',
    storageBucket: 'datedawn.firebasestorage.app',
    measurementId: 'G-GF48EGQGFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6xFv-bW3lj5v0hkf4vMyxSvc6eeJ6Wo',
    appId: '1:255395342604:android:5f4ad705bcbfa62cf10129',
    messagingSenderId: '255395342604',
    projectId: 'datedawn',
    storageBucket: 'datedawn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKeDdWuopUS2lSBZENz8kuUwqSNo6E_3g',
    appId: '1:255395342604:ios:fd2cccaa18e03ca7f10129',
    messagingSenderId: '255395342604',
    projectId: 'datedawn',
    storageBucket: 'datedawn.firebasestorage.app',
    iosBundleId: 'com.datedawn.app',
  );
}
