// Deep-clean regenerable build output.
//
//   node scripts/deep-clean.mjs --dry-run    (default: report only)
//   node scripts/deep-clean.mjs --apply
//
// ## Why this is an allowlist and not `git clean -Xdf`
//
// The obvious way to do this is "delete everything git ignores". On this repo
// that would be **catastrophic**, because the ignore file also covers:
//
//   android/app/google-services.json   the Firebase project config
//   android/key.properties             the Android signing credentials
//   .env.local                         environment secrets
//   .neon                              Neon project binding
//   ios/Runner/GoogleService-Info.plist
//
// None of those are junk and none are regenerable by a build command. A blanket
// ignore-clean deletes all of them and there is no way back — they are not in
// git, which is exactly why deleting them is unrecoverable.
//
// So: an explicit allowlist of build artifacts only. Every entry is proof-checked
// against `.gitignore` and against git's tracked-file list before removal, and
// anything that looks like configuration is refused even if it is listed.

import { execSync } from 'node:child_process';
import { existsSync, rmSync, statSync } from 'node:fs';
import { readdirSync } from 'node:fs';
import { join } from 'node:path';

const APPLY = process.argv.includes('--apply');

/// Regenerable build output. Each is reproduced by a documented command.
const TARGETS = [
  { path: 'build', why: 'flutter build / npm run build:web', cmd: 'npm run build:web' },
  { path: '.dart_tool', why: 'pub + build caches', cmd: 'flutter pub get' },
  { path: 'node_modules', why: 'npm packages', cmd: 'npm install' },
  { path: 'android/.gradle', why: 'Gradle user cache', cmd: 'flutter build appbundle' },
  { path: 'android/app/build', why: 'Gradle module output', cmd: 'flutter build appbundle' },
  { path: 'android/build', why: 'Gradle root output', cmd: 'flutter build appbundle' },
  { path: 'ios/Pods', why: 'CocoaPods (regenerated by pod install)', cmd: 'pod install' },
  { path: 'ios/.symlinks', why: 'CocoaPods symlinks', cmd: 'pod install' },
  { path: 'macos/Pods', why: 'CocoaPods', cmd: 'pod install' },
  { path: 'windows/flutter/ephemeral', why: 'Flutter ephemeral', cmd: 'flutter pub get' },
  { path: 'linux/flutter/ephemeral', why: 'Flutter ephemeral', cmd: 'flutter pub get' },
];

/// Never removed, even if a pattern above would match. Kept as a second net —
/// these are configuration, credentials, or source.
const NEVER = [
  'google-services.json',
  'GoogleService-Info.plist',
  'key.properties',
  '.env.local',
  '.neon',
  'pubspec.lock',
  'package-lock.json',
  '.gitignore',
];

/// Directories that would be a disaster to remove from the repo root.
const FORBIDDEN_ROOTS = ['.git', 'lib', 'test', 'assets', 'web', 'ios/Runner',
  'android/app/src', 'scripts', 'pubspec.yaml', 'package.json'];

function size(p) {
  let total = 0;
  for (const entry of readdirSync(p, { withFileTypes: true })) {
    const full = join(p, entry.name);
    try {
      total += entry.isDirectory() ? size(full) : statSync(full).size;
    } catch {
      // A symlink or a racing delete; skip it.
    }
  }
  return total;
}

const mb = (b) => (b / 1048576).toFixed(1);

// A tracked file under a directory we are about to delete means the directory
// holds source, and deleting it would destroy work. Verify before touching.
function trackedCount(dir) {
  try {
    const out = execSync(`git ls-files -- "${dir}"`, { encoding: 'utf8' });
    return out.split('\n').filter((l) => l.trim()).length;
  } catch {
    return -1;
  }
}

let freed = 0;
const planned = [];

for (const target of TARGETS) {
  if (!existsSync(target.path)) continue;

  const name = target.path.split('/').pop();
  if (NEVER.includes(name)) {
    console.log(`  SKIP  ${target.path}  (protected configuration)`);
    continue;
  }
  if (FORBIDDEN_ROOTS.includes(target.path)) {
    console.log(`  SKIP  ${target.path}  (listed in FORBIDDEN_ROOTS)`);
    continue;
  }

  const tracked = trackedCount(target.path);
  if (tracked > 0) {
    console.log(
      `  SKIP  ${target.path}  (${tracked} tracked file(s) — this is source)`,
    );
    continue;
  }

  const bytes = size(target.path);
  freed += bytes;
  planned.push(target);

  console.log(
    `  ${APPLY ? 'REMOVE' : 'WOULD '} ${target.path.padEnd(28)} ` +
    `${mb(bytes).padStart(8)} MB   <- ${target.why}`,
  );
}

console.log('');
if (planned.length === 0) {
  console.log('Nothing to clean. The tree is already lean.');
  process.exit(0);
}

if (!APPLY) {
  console.log(`Reclaimable: ${mb(freed)} MB across ${planned.length} path(s).`);
  console.log('\nRe-run with --apply to remove them.');
  console.log('\nRegenerate everything with:');
  const cmds = [...new Set(planned.map((t) => t.cmd))];
  for (const c of cmds) console.log(`  ${c}`);
  process.exit(0);
}

let removed = 0;
for (const target of planned) {
  try {
    rmSync(target.path, { recursive: true, force: true });
    removed += 1;
  } catch (error) {
    console.error(`  FAILED ${target.path}: ${error.message}`);
  }
}

console.log(`Removed ${removed}/${planned.length} path(s), freeing ${mb(freed)} MB.`);
console.log('\nRegenerate with:');
for (const c of [...new Set(planned.map((t) => t.cmd))]) console.log(`  ${c}`);
